# Generated by Django 6.0.3 on 2026-03-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestion',
            old_name='año',
            new_name='anio',
        ),
    ]
