# Generated by Django 6.0.3 on 2026-03-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_año_gestion_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='academic.nivel'),
        ),
        migrations.AddConstraint(
            model_name='grado',
            constraint=models.UniqueConstraint(fields=('nivel', 'nombre'), name='unique_grado_nivel'),
        ),
    ]
