# Generated by Django 6.0.3 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_grado_nivel_grado_unique_grado_nivel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grado',
            name='unique_grado_nivel',
        ),
        migrations.AddConstraint(
            model_name='grado',
            constraint=models.UniqueConstraint(fields=('nivel', 'nombre'), name='unique_grado_por_nivel'),
        ),
    ]
