# Generated by Django 6.0.3 on 2026-03-29 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_grado_unique_grado_nivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paralelo',
            options={'ordering': ['grado', 'letra']},
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='cupo_max',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='academic.grado'),
        ),
        migrations.AddConstraint(
            model_name='paralelo',
            constraint=models.UniqueConstraint(fields=('grado', 'letra'), name='unique_paralelo_por_grado', violation_error_message='Este paralelo ya existe para el grado seleccionado.'),
        ),
        migrations.AlterConstraint(
            model_name='grado',
            name='unique_grado_por_nivel',
            constraint=models.UniqueConstraint(fields=('nivel', 'nombre'), name='unique_grado_por_nivel', violation_error_message='Ya existe este grado registrado en el nivel seleccionado.'),
        ),
    ]
