# Generated by Django 6.0.3 on 2026-04-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
